print ("Salvacion,WarrenBopp L") 
print ("Barangay dos")
print ("April 14, 1997")
print ("Marinduque State College")
print ("BSIT/2E")
print ("My Hobbies")
print ("Basketball")
print ("Dancing")
print ("Singing")
print ("Eating")
print ("Travel")

